### ISSUE TITLE
Playoff Summary

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#227]
In the Cheat Sheet page, there is a link to a playoff summary. I don't think that is the correct file. I have a different (and better in my opinion) summary page. ("Here is a very useful summary for the playoffs, provided by Bill Aucoin.")

**Comment by WBAucoin** [comment]
I'll find the one that I recommend get posted and post it here.

**Comment by jameslockman** [comment]
Thank you.

**Comment by jameslockman** [comment]
I updated that from last year's version. Do you see one for 2024?

**Comment by WBAucoin** [comment]
What is in there now is a compilation of data from the game manual. I have
a home-grown two-sided playoff schedule of which I am proud.

**Comment by WBAucoin** [comment]
I need to verify the information is correct against the game manual. Last year, there was Team Update 16 which clarified what to do with a tie in the Finals. I have not done that yet.

**Comment by jameslockman** [comment]
We are using the same criteria as last year. Ties are ties, until the third OVERTIME match. Then, we use the criteria in table 10-3, shown in 10.6.2.1 See [https://firstfrc.blob.core.windows.net/frc2024/Manual/Sections/2024GameManual-10Tournaments.pdf](https://firstfrc.blob.core.windows.net/frc2024/Manual/Sections/2024GameManual-10Tournaments.pdf)

**10.6.2.2 Playoff Finals**
Once a single ALLIANCE remains in each Upper and Lower bracket, those ALLIANCES proceed to the Finals
round. The first ALLIANCE to win 2 MATCHES in the Finals becomes the event’s Champions.
If a Finals MATCH ends in a tie score, the tie is not broken using the criteria in Table 10-3, the MATCH remains
a tie. In the case where an ALLIANCE hasn’t won 2 MATCHES after 3 MATCHES have been played (because of
tied MATCHES), the Playoffs proceed with up to 3 additional Finals MATCHES, called Overtime MATCHES, until
an ALLIANCE has won 2 Finals MATCHES. In the case where the Overtime MATCH scores for both ALLIANCES
are equal, the win for that Overtime MATCH is awarded based on the criteria listed in Table 10-3.

**Comment by WBAucoin** [comment]
I don't think this was completed. I recommend you link to the attached file.
[2024 Typical Playoff MATCH Schedule, v1.pdf](https://github.com/arthurlockman/gatool-ui/files/14385673/2024.Typical.Playoff.MATCH.Schedule.v1.pdf)

**Comment by jameslockman** [comment]
Done.

**Comment by WBAucoin** [comment]
Thanks! We’ll likely have to replace it with a tweaked version. I just got some review comments from Blair.

**Comment by WBAucoin** [comment]
We need to upload the latest one that Blair approved.

**Comment by jameslockman** [comment]
It is there. Clear your cache.
