### ISSUE TITLE
Alliance Selection teams in wrong order, even though Rankings is correct

### ISSUE THREAD

**Issue by jameslockman** [arthurlockman/gatool-ui#282]
User reports that Alliance Selection screen shows teams in wrong order, even though the rankings are correct. Tapping the red button to refresh does not rectify the issue. We know that there are cases where restarting Alliance Selection will fix it, but that is not obvious to the user. 

Please:

- Determine why Alliance Selection is not in the right order at the start
- Potentially add "restart Alliance Selection" to the refresh Rankings flow on the Alliance Selection page

**Comment by klardotsh** [comment]
This is still an issue for me this week at PNW SunDome for the third week in a row (also happened at CanPac wk1 where I was the "User report" mentioned in OP, and again at PNW Auburn last week).

I have been running alliance selections using paper rankings printout from FMS + the awards screen for all three events. The GATool AS screen never has the right ranks.

A huge win for me, though I'm not sure how much of a nightmare on the technical end, would be the ability to fully construct my own Alliance Selection rankings list independently of whatever rankings state GATool thinks it has. By manual I'm less thinking "get the FTA to email me an excel sheet", and more "can I please just transcribe the paper printout from the scoring table manually into a series of input boxes I can tab-button between" - or even the dropdown UI widget used for practice match/backup bot selection might be fine, if a bit slower for those of us on laptops.

Bonus: I've seen at least one case where (if memory serves) I think the ranking tab in GATool and the rankings/promotion criteria on the AS tab did not agree - IIRC that was the case at PNW Auburn last week, where I checked the rankings tab, it was correct, then I went to the AS screen and forcibly unlocked (since I got the bouncer screen warning me things might be wrong), and... captain promotion was wrong, and I fell back to using the awards screen again instead.
