### ISSUE TITLE
2024 Game Manual Update - Melody Points Needed for Ranking Point

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#355]
The Cheat Sheet is out of date since Team Update 18 increased the number of Notes for a Ranking Point for District Championships.
https://firstfrc.blob.core.windows.net/frc2024/Manual/TeamUpdates/TeamUpdates-combined.pdf

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/9053180d-8e45-41b9-95ba-4bc02831ec12)

![image](https://github.com/arthurlockman/gatool-ui/assets/139565335/caabd9cc-6253-44cd-ab13-52ff43cf707a)

**Comment by jameslockman** [comment]
Well, it only applies to Disrict Champs now, not to all events going forward, right? Offseason events will be at 18, I think, and we don’t know yet what will be the threshold for Houston.


James

James Lockman  |  Group Manager, Customer Success Americas  |  Adobe  |  T +1 917 934 0849  |  C +1 917 284 2268  |  ***@***.******@***.***>



From: WBAucoin ***@***.***>
Date: Monday, April 1, 2024 at 4:31 PM
To: arthurlockman/gatool-ui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [arthurlockman/gatool-ui] 2024 Game Manual Update - Melody Points Needed for Ranking Point (Issue #355)

EXTERNAL: Use caution when clicking on links or opening attachments.



The Cheat Sheet is out of date since Team Update 18 increased the number of Notes for a Ranking Point for District Championships.
https://firstfrc.blob.core.windows.net/frc2024/Manual/TeamUpdates/TeamUpdates-combined.pdf

image.png (view on web)<https://github.com/arthurlockman/gatool-ui/assets/139565335/9053180d-8e45-41b9-95ba-4bc02831ec12>

image.png (view on web)<https://github.com/arthurlockman/gatool-ui/assets/139565335/caabd9cc-6253-44cd-ab13-52ff43cf707a>

**Comment by WBAucoin** [comment]
I agree [that it only applies to District Championships]. I expect that
another Team Update will increase the number of notes for a MELODY RP for
the Houston World CMP. I will be announcing, with John Edwards, at the
FIRST CHS DCMP. I am setup to use your cheat sheet as a ready reference.
I'll have to remember that it is incorrect (or edit it offline) for my own
reference.

**Comment by jameslockman** [comment]
I'll not be adding a special version of cheat sheet just for District Champs events. The audience display has the right thresholds in real time.

**Comment by WBAucoin** [comment]
OK.
