### ISSUE TITLE
Auto Advance Wipes Out Backup Robots in Playoffs

### ISSUE THREAD

**Issue by WBAucoin** [arthurlockman/gatool-ui#374]
If you have auto advance on and enter backup robots into gatool during the playoffs, the next auto advance will wipe out the backup robots and will revert you back to the original alliance robots.

**Comment by jameslockman** [comment]
This is true if your event data from FIRST hasn't caught up with your event. FIRST data is canonical, from the gatool perspective, and if we get new data, outdated or otherwise, it will "win" over any local overrides. Know that the additional team will come back in the lineup the next time the Alliance appears in the Playoffs, because the Alliance will have been updated by FMS.

**Comment by WBAucoin** [comment]
I was bullish on using auto advance today until that happened. I setup like
I would be in Houston (gaNest light) and followed some events. When the
auto advance wiped the backup teams, I was without the backup teams’
information. I guess I could use it during quais and turn it off for
playoffs.
